### ISSUE TITLE
Possible to give suggestion on how to build please?

### ISSUE THREAD

**Issue by simonm** [aleios/gw2-cursoroverride#1]
Hello - is it possible you could give any hints on how to compile this project? It's exactly what I need. 

I've tried using msvc-x64-cmake package on Arch but I'm not familiar with it and am getting errors. Any advice would be really appreciated. This is the last thing I need to 100% move to GW2 on Linux...

**Comment by simonm** [comment]
Or if you could even provide the DLL pre-compiled, it would be amazing.

**Comment by aleios** [comment]
No problem mate. There should be a release here https://github.com/aleios/gw2-cursoroverride/releases/tag/1.0

Should still work. I haven't had to recompile at least. It'll just replace the mouse with whatever cursor.png is.

Would be interested though in the errors that you've been getting?

**Comment by simonm** [comment]
Thank you so much. I don't know why I didn't find that.... Cheers!

**Comment by aleios** [comment]
No problem mate. Good luck
